name: finlisty
description: A Personal Finance mobile app for Bangladesh.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.0.0
  firebase_messaging: ^15.0.0
  
  # State Management & Architecture
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  dartz: ^0.10.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  
  # UI
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
